Cancel all asyncio tasks before exiting to avoid RuntimeError
When the loop is closed before Tasks are finished or cancelled, there is a
RuntimeError raised:

Exception ignored in: <coroutine object Episode.download at 0x10d0008c8>
Traceback (most recent call last):
  File ".../simple-podcast-dl/podcast_dl/podcast_dl.py", line 29, in download
    async with semaphore:
  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/asyncio/locks.py", line 92, in __aenter__
    await self.acquire()
  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/asyncio/locks.py", line 477, in acquire
    fut.cancel()
  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 672, in call_soon
    self._check_closed()
  File "/usr/local/var/pyenv/versions/3.7.0/lib/python3.7/asyncio/base_events.py", line 461, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<Episode.download() done, defined at .../simple-podcast-dl/podcast_dl/podcast_dl.py:28> wait_for=<Future cancelled> cb=[_wait.<locals>._on_completion() at /usr/local/var/pyenv/versions/3.7.0/lib/python3.7/asyncio/tasks.py:436]>

because they could not be finished properly, so for a clean shutdown, we need
to cancel every running tasks. See:
https://docs.python.org/3.6/library/asyncio-dev.html#asyncio-pending-task-destroyed
and
https://stackoverflow.com/questions/40897428/please-explain-task-was-destroyed-but-it-is-pending

asyncio surprisingly react way better to CTRL-C than a thread pool, it actually
stops already at the first press, no need to to all kind of magic, and at the
end it will exit cleanly.